### PR TITLE
Prepare for Homebridge v2

### LINKED ISSUE #958: Homebridge v2.0 Breaking Updates
**Please describe the problem:**

I am not sure if you are aware but the next version of Homebridge (v2.0) comes with breaking changes for a lot of Homebridge plug-ins and it has been put on the developers to update their plug-ins.

[For Plug-In Developers](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2#for-plugin-developers)

I have tested this plug-in on the beta version and it will crash Homebridge.

**Describe the solution you'd like:**
Please have a read of the link above and see what changes are required for this plug-in.

**Describe alternatives you've considered:**
All users of this plug-in will have to remain on Homebridge v1.8.4.

**Additional context:**
image

### PR DESCRIPTION
**Pull request by afharo**
Resolves #958

@mitch7391, would you mind helping me figure out if these changes are enough?

Is it safe to merge for the current version of Homebridge? (my tests tend to indicate it is, and I checked HAP-Nodejs' code and it looks like 0.12 supports both, but I'd like to confirm).

### CODE REVIEW

**Comment by mitch7391** [comment]
@afharo happy to test it out for you, any chance you can make a beta release for my ease? With newborn twins I have very little time to go about cloning the repo and installing on my dev machine :)

**Comment by afharo** [comment]
@mitch7391, sure! I'll publish it maybe tonight.

Wow! Twins!! Congrats! I have 2 kids (1 and 3 y/o) and it's madness here. I can't imagine having newborn twins! 🫨

**Comment by mitch7391** [comment]
Cheers :) I am not sure how people go back for more, we got a boy and a girl, so we are done now! :D it has been pretty full on but we are smitten!

Also, I should have provided logs earlier for you (will paste here and in the original issue):

```
[27/07/2024, 3:19:31 pm] [Roborock] Restarting Process...
[27/07/2024, 3:19:33 pm] [Roborock] Launched child bridge with PID 17443
[27/07/2024, 3:19:33 pm] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[27/07/2024, 3:19:33 pm] [Roborock] Loaded homebridge-xiaomi-roborock-vacuum v0.31.1 child bridge successfully
[27/07/2024, 3:19:33 pm] Loaded 0 cached accessories from cachedAccessories.0E8A2B113731.
TypeError: this.hap.Service.BatteryService is not a constructor
    at new BatteryInfo (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/battery_info.ts:11:20)
    at XiaomiRoborockVacuum.initializeServices (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/xiaomi_roborock_vacuum_accessory.ts:111:16)
    at new XiaomiRoborockVacuum (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/xiaomi_roborock_vacuum_accessory.ts:80:32)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:177:52)
[27/07/2024, 3:19:34 pm] [Roborock] Child bridge process ended
[27/07/2024, 3:19:34 pm] [Roborock] Process Ended. Code: 1, Signal: null
```
From a brief look at yours changes, I think that should work!

**Comment by afharo** [comment]
One week later, I published `homebridge-xiaomi-roborock-vacuum@0.32.0-beta.0` 😅 

I hope the twins are giving you a break.

**Comment by afharo** [comment]
I deployed it in my own home to fully test it out (testing it with `homebridge@2.0.0-beta.11` 😇 )

**Comment by mitch7391** [comment]
Sorry for the late reply @afharo, been a busy few days! Will try give it a go in the next day or two 😊

**Comment by afharo** [comment]
Thanks for confirming! 🧡  

I'll go ahead and merge this PR then :)

**Pull request merged**
