### PR TITLE
Updated behaviour of the `go to` button

### PR DESCRIPTION
**Pull request by luc-ass**
#### Changes
- `go to` button stays on as long as the status is `going-to-coordinates` or `waiting`, enabling you to turn the button off manually
- turning off the button results in `activateCharging()`, effectively sending the vacuum back to its dock
- this also enables you to switch off a scene in automations automatically, thus sending the vacuum home if nothing happens. This should prevent the battery to run low or the vacuum becoming unresponsive/asleep

### CODE REVIEW

**Comment by luc-ass** [comment]
I was able to perform quite some testing: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/539#issuecomment-1237715502

**Comment by luc-ass** [comment]
I have no idea what causes Prettier to fail. My vscode doesn't complain at all.

**Comment by afharo** [comment]
@luc-ass next time running `npm run lint:fix` should automatically fix any issues :)

**Review by afharo — APPROVED** [review]
LGTM! Thank you for fixing this!

**Comment by luc-ass** [comment]
> @luc-ass next time running `npm run lint:fix` should automatically fix any issues :)

Thanks for your input. I'd appreciate it, if you could have a look at your code editor and wether saving the file results in trailing commas for you 🙏

**Comment by afharo** [comment]
> > @luc-ass next time running `npm run lint:fix` should automatically fix any issues :)
> 
> 
> 
> Thanks for your input. I'd appreciate it, if you could have a look at your code editor and wether saving the file results in trailing commas for you 🙏 

I had to set my code editor to apply prettier on save. What editor do you use?

We could also create a precommit hook that automatically fix these when running git commit.

And I'd like to improve the CI error to remember that running `npm run lint:fix` should fix any lint issues. Even more! CI could push that for us 😇

I need to figure that out with Github actions.

**Comment by luc-ass** [comment]
It's so strange, that the editors seem to behave differently. I am using vscode. It lints my code using Prettier on save, grabbing the configuration from `.vscode/settings.json` and thus applying `"prettier.trailingComma": "all"`. 

__My take on this is:__
All that seems to work as intended, but when the github workflow runs `npm run lint` [(link)](https://github.com/luc-ass/homebridge-xiaomi-roborock-vacuum/blob/9e7884030a28a537e1ec3c24388811060dad6075/.github/workflows/nodejs.yml#L26) this results in actually running `prettier --check .` [(link)](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/954eb1d175354747f12694b261f9712c47947f66/package.json#L46). This doesn't happen in a vscode-environment, so it uses the standard linting rules, falling back to __es5__ [(docs)](https://prettier.io/docs/en/options.html#trailing-commas), which doesn't allow trailing commas everywhere for backwards compatibility.

__Fixes:__
_.vscode/settings.json_
```
"prettier.trailingComma": "es5"
```
__OR__
_package.json_
```
"lint": "prettier --check --trailing-commas all .",
```

**Comment by afharo** [comment]
@luc-ass it makes perfect sense.

IMO, instead of changing the lint and fix commands, I think it's best to create a prettier config file `.prettierrc` where we can set our custom configs like the one you mentioned.

WDYT?

**Pull request merged**
