### PR TITLE
Fixed: push room names from settings to homekit

### PR DESCRIPTION
**Pull request by YoeriVD**
#828

### CODE REVIEW

**Review by afharo — APPROVED** [review]
Oh! Thank you for figuring it out!!! 🧡

**Comment by afharo** [comment]
Released in 0.31.0: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.31.0

**Comment by maisun** [comment]
Tried the new version but looks like there are still no names..

**Comment by afharo** [comment]
@maisun, just to clarify: this is fixing the iOS16 bug where all "buttons" would have the same name. This is not automatically retrieving the room names from the robot. Is that what you referred to?

**Comment by maisun** [comment]
> @maisun, just to clarify: this is fixing the iOS16 bug where all "buttons" would have the same name. This is not automatically retrieving the room names from the robot. Is that what you referred to?

Hi, ok thanks I was thinking it solves this issue with iOS 17: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/800

**Pull request merged**
