### PR TITLE
Xiaowa e202 02 charging issue

### PR DESCRIPTION
**Pull request by bedrin**
This PR fixes https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/180 and is based on top of https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/179

It works great for me Xiaowa E202-02 with one minor issue (see below)
However I'm not able to test it with other models - probably switching from `stop` to `pause` would break other models.

Outstanding issue: when I change the fan speed it does work but the Home app on my iOS shows "No Response" unless I restart the Home application.

It can be solved using a dirty hack of removing "await" from `await this.device.changeFanSpeed(miLevel);` call, but it obviously results in following errors in logs:
```
(node:2956) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
    at checkResult (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio-nicoh88/lib/devices/vacuum.js:16:9)
(node:2956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

I didn't include it to this PR and still do not understand what's wrong about it - probably something wrong in `changeFanSpeed` implementation inside `miio` for this model

### CODE REVIEW

**Comment by afharo** [comment]
Hi @bedrin! Thank you for your PR (both of them)!

I'm afraid there are some conflicts in the PR with `master` (we had some pending changes (https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/167) to be merged in the `next` branch and they created conflicts once merged to `master`). Do you mind amending your files to match the new implementation?

Also, I'm a bit concerned with the `pause` change that may affect the rest of the models. Maybe an `if model === X` conditional would be safer here?

Re the "No Response" issue. That's very odd. Are we sure those are the valid modes accepted by that model?

**Comment by bedrin** [comment]
> I'm afraid there are some conflicts in the PR with `master` (we had some pending changes (#167) to be merged in the `next` branch and they created conflicts once merged to `master`). Do you mind amending your files to match the new implementation?

I've resolved conflicts

> Also, I'm a bit concerned with the `pause` change that may affect the rest of the models. Maybe an `if model === X` conditional would be safer here?

That was my concern as well. I have only one model so cannot say for sure.
Let me make it conditional for this model - it's the safest option.

> Re the "No Response" issue. That's very odd. Are we sure those are the valid modes accepted by that model?

Yes, modes are changed correctly - and shown correctly in Mi Home application as well.
I don't have an explanation for it yet. I have a theiry that some models are ARM based while others (including my Xiaowa) are ESP based - hence completelly different (although similar) implementations.


Also after playing with the vacuum for another day I've noticed another bug. When vacuum finishes the cleaning and goes to dock, my iPhone still shows it as active.

**Comment by afharo** [comment]
I've repointed this PR to the `next` branch so we can merge it and publish a beta version `0.9.0` so we can use our time to test it thoroughly :)

**Comment by bedrin** [comment]
> Also after playing with the vacuum for another day I've noticed another bug. When vacuum finishes the cleaning and goes to dock, my iPhone still shows it as active.

This one doesn't seem to be specific to my Xiaowa - others also report this issue:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/146

**Pull request merged**
